export const FETCH_RESTAURANTS = 'FETCH_RESTAURANTS';
export const FETCH_RESTAURANT = 'FETCH_RESTAURANT';
export const UPDATE_RESTAURANT = 'UPDATE_RESTAURANT';
export const POST_REVIEW = 'POST_REVIEW';
export const TEXT_FILTER = 'TEXT_FILTER';
export const CATEGORY_FILTER = 'CATEGORY_FILTER';
